"""make contract template_id nullable for template deletion

Revision ID: 0ac7887e9d25
Revises: c1e71d4b6555
Create Date: 2026-06-15 14:23:52.000150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac7887e9d25'
down_revision: Union[str, None] = 'c1e71d4b6555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'template_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'template_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
