"""add archive fields to contracts

Revision ID: c1e71d4b6555
Revises: db67a6e4087e
Create Date: 2026-06-13 21:50:17.738524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1e71d4b6555'
down_revision: Union[str, None] = 'db67a6e4087e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('status_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'status_history')
    op.drop_column('contracts', 'archived_at')
    # ### end Alembic commands ###
